name: Weekly research triage

# ――――――――――――――――――――――――――――――――――――――――――
# Triggers
# ①  Runs every Friday at 13:00 UTC
# ②  Can be launched manually from the Actions tab
# ――――――――――――――――――――――――――――――――――――――――――
on:
  schedule:
    - cron: '0 13 * * 5'      # every Friday, 13:00 UTC
  workflow_dispatch:

# Allow this workflow to push new commits
permissions:
  contents: write

jobs:
  triage-inbox:
    runs-on: ubuntu-latest

    steps:
      # 1  Check out the repo
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0            # so we can commit back

      # 2  Set up Python
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 3  Install helper libraries
      - name: Install dependencies
        run: |
          pip install --upgrade \
            PyGithub \
            "openai>=1.0.0" \
            requests \
            readability-lxml \
            html2text \
            youtube_transcript_api

      # 4  Run the triage script (fetch → summarise → write MD → relabel)
      - name: Run triage script
        env:
          GH_PAT:          ${{ secrets.GH_PAT }}
          OPENAI_API_KEY:  ${{ secrets.OPENAI_API_KEY }}
        run: python scripts/triage_inbox.py

      # 5  Commit any new notes back to main
      - name: Commit summaries
        run: |
          git config user.name  "triage-bot"
          git config user.email "bot@example.com"
          git add research/processed || true
          git commit -m "chore: auto-triage research inbox" || echo "Nothing to commit"
          git push
